CREATE OR REPLACE VIEW VW_041_ELEICAO_SEGUNDO_TURNO AS (
        SELECT DISTINCT EL.CD_ELEICAO ,
                        EL.CD_PLEITO ,
                        TA.CD_TIPO_ABRANGENCIA,
                        CT.SG_UE_UF ,
                        DECODE(EL.CD_TIPO_ABRANGENCIA, 0, CT.SG_UE, '0') NR_MUNICIPIO,
                        CT.CD_CARGO 
          FROM ELEICAO EL, CANDIDATO CT, TIPO_ABRANGENCIA TA
         WHERE EL.CD_PLEITO = CT.CD_PLEITO
           AND EL.CD_ELEICAO = CT.CD_ELEICAO
           AND CT.CD_SITUACAO_TOTALIZACAO = 6
           AND CT.CD_CARGO IN (1,3,11)
           AND EL.CD_TIPO_ABRANGENCIA = TA.CD_TIPO_ABRANGENCIA);
