CREATE OR REPLACE VIEW VW_021_SECAO_IMPORTACAO_SECOES AS
SELECT SEP.CD_PLEITO,
       SP.SG_UE_UF,
       UP.SG_UE CD_MUNICIPIO,
       UP.NM_UE NM_MUNICIPIO,
       LPAD(SP.NR_ZONA, 4, '0') NR_ZONA,
       LPAD(SP.NR_LOCAL, 4, '0') NR_LOCAL_VOTACAO,
       LV.NM_LOCAL NM_LOCAL_VOTACAO,
       LV.DS_ENDERECO DS_ENDERECO_LOCAL_VOTACAO,
       SP.CD_TIPO_LOCAL_VOTACAO,
       LPAD(SP.NR_SECAO, 4, '0') NR_SECAO,
       (SELECT listagg(LPAD(SP2.NR_SECAO, 4, '0'), '/') WITHIN GROUP (ORDER BY SP2.NR_SECAO)
       FROM SECAO_PROCESSO SP2
       WHERE SP2.NR_SECAO_PRINCIPAL = SP.NR_SECAO
			 AND SP2.SG_UE_UF = SP.SG_UE_UF
             AND SP2.SG_UE_MUN = SP.SG_UE_MUN
             AND SP2.NR_ZONA = SP.NR_ZONA
             AND SP2.NR_SECAO_PRINCIPAL IS NOT NULL
             AND SP2.CD_PROCESSO_ELEITORAL = SP.CD_PROCESSO_ELEITORAL) SECOES_AGREGADAS,
       NVL((SELECT DISTINCT QT_APTOS
       FROM SECAO_ELEICAO SE2
       INNER JOIN ELEICAO EL2
             ON SE2.CD_ELEICAO = EL2.CD_ELEICAO
       WHERE EL2.CD_TIPO_ABRANGENCIA = 0 --Abrangencia municipal
             AND SE2.CD_PLEITO = SEP.CD_PLEITO
             AND SE2.SG_UE_UF = SEP.SG_UE_UF
             AND SE2.SG_UE_MUN = SEP.SG_UE_MUN
             AND SE2.NR_ZONA = SEP.NR_ZONA
             AND SE2.NR_SECAO = SEP.NR_SECAO),0) QT_APTOS_MUNICIPAIS,
       NVL((SELECT DISTINCT QT_APTOS
       FROM SECAO_ELEICAO SE3
       INNER JOIN ELEICAO EL3
             ON SE3.CD_ELEICAO = EL3.CD_ELEICAO
       WHERE EL3.CD_TIPO_ABRANGENCIA = 1 --Abrangencia estadual
             AND SE3.CD_PLEITO = SEP.CD_PLEITO
             AND SE3.SG_UE_UF = SEP.SG_UE_UF
             AND SE3.SG_UE_MUN = SEP.SG_UE_MUN
             AND SE3.NR_ZONA = SEP.NR_ZONA
             AND SE3.NR_SECAO = SEP.NR_SECAO),0) QT_APTOS_ESTADUAIS,
       NVL((SELECT DISTINCT QT_APTOS
       FROM SECAO_ELEICAO SE4
       INNER JOIN ELEICAO EL4
             ON SE4.CD_ELEICAO = EL4.CD_ELEICAO
       WHERE EL4.CD_TIPO_ABRANGENCIA = 2 --Abrangencia federal
             AND SE4.CD_PLEITO = SEP.CD_PLEITO
             AND SE4.SG_UE_UF = SEP.SG_UE_UF
             AND SE4.SG_UE_MUN = SEP.SG_UE_MUN
             AND SE4.NR_ZONA = SEP.NR_ZONA
             AND SE4.NR_SECAO = SEP.NR_SECAO),0) QT_APTOS_FEDERAIS,
			 tl.nm_tipo_local_votacao
FROM SECAO_PROCESSO SP
INNER JOIN UE_PROCESSO UP
      ON SP.SG_UE_MUN = UP.SG_UE
      AND SP.CD_PROCESSO_ELEITORAL = UP.CD_PROCESSO_ELEITORAL
INNER JOIN SECAO_PLEITO SEP
      ON SP.CD_PROCESSO_ELEITORAL = SEP.CD_PROCESSO_ELEITORAL
      AND SP.SG_UE_UF = SEP.SG_UE_UF
      AND SP.SG_UE_MUN = SEP.SG_UE_MUN
      AND SP.NR_ZONA = SEP.NR_ZONA
      AND SP.NR_SECAO = SEP.NR_SECAO
INNER JOIN LOCAL_VOTACAO LV
      ON LV.CD_PROCESSO_ELEITORAL = SP.CD_PROCESSO_ELEITORAL
      AND LV.SG_UE_UF = SP.SG_UE_UF
      AND LV.NR_ZONA = SP.NR_ZONA
      AND LV.SG_UE_MUN = SP.SG_UE_MUN
      AND LV.NR_LOCAL = SP.NR_LOCAL
INNER JOIN tipo_local_votacao tl
      ON sp.cd_tipo_local_votacao = tl.cd_tipo_local_votacao
WHERE SP.NR_SECAO_PRINCIPAL IS NULL;