CREATE OR REPLACE VIEW VW_114_CONSULTA_ACOMPANHAMENTO_IMPORTACAO AS
SELECT  A.ID_ELEITORAL AS IDELEITORAL,
		A.CD_TIPO_PACOTE AS TIPOPACOTE,
		A.CD_TIPO_SITUACAO_AGENDAMENTO AS CODIGOTIPOSITUACAOAGENDAMENTO,
        A.SG_UE_UF AS SIGLAUF, 
        A.SG_UE AS SIGLAUE, 
        U.NM_UE AS NOME, 
        A.NR_ZONA AS NUMEROZONA, 
        T.NM_TIPO_SITUACAO_AGENDAMENTO AS SITUACAO,
        A.TX_ERRO_OCORRIDO AS DESCRICAOERRO,
        A.DT_AGENDAMENTO_IMPORTACAO AS DATAAGENDAMENTO,
        A.DT_INI_IMPORTACAO AS DATAINIIMPORTACAO,
        A.DT_FIM_IMPORTACAO AS DATAFIMIMPORTACAO
FROM AGENDAMENTO_IMPORTACAO A 
JOIN UE U ON (A.SG_UE = U.SG_UE)
JOIN TIPO_SITUACAO_AGENDAMENTO T ON (A.CD_TIPO_SITUACAO_AGENDAMENTO = T.CD_TIPO_SITUACAO_AGENDAMENTO);
